# values.yaml

job:
  name: ztp-update-job
  image:
    repository: harbor.st0788.cgw-hpe.net/library/gl-edge-master-repo:gen-image2
  command: ["python3", /app/"orchestrator.py"]

store_info:
  store_id: ST0788
