# templates/job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.job.namespace }}
  
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.job.name }}
        image: {{ .Values.job.image.repository }}
        command: ["python3", "/app/orchestrator.py", "{{ .Values.job.numberOfNodes }}", "{{ .Values.job.depot_file }}", "{{ .Values.job.opsmode }}" ] 
        env:
        - name: domainname
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#domainname>
        - name: vCenterClusterName
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#vCenterClusterName>
        - name: vCenterIp
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#vCenterIp>
        - name: vCenterDCName
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#vCenterDCName>
        - name: vCenterUsername
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#vCenterUsername>
        - name: vCenterPassword
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#vCenterPassword>
        - name: pulpusername
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#pulpusername>
        - name: pulppassword
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#pulppassword>
        - name: tenantID
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#tenantId>

        - name: server1ILOUsername
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1ILOUsername>
        - name: server1ILOPassword
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1ILOPassword>
        - name: server1LocalDataStore
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1LocalDataStore>
        - name: server1MgmtIP
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1MgmtIP>
        - name: server1OsUsername
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1OsUsername>
        - name: server1OsPassword
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1OsPassword>
        - name: server1ILOHostname
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1ILOHostname>
        - name: server1FQDN
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server1FQDN>  

        - name: server2ILOUsername
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2ILOUsername>
        - name: server2ILOPassword
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2ILOPassword>
        - name: server2LocalDataStore
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2LocalDataStore>
        - name: server2MgmtIP
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2MgmtIP>
        - name: server2OsUsername
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2OsUsername>
        - name: server2OsPassword
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2OsPassword>
        - name: server2ILOHostname
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2ILOHostname>
        - name: server2FQDN
          value: <path:{{ .Values.store_info.store_id}}/edge-config/data/secrets#server2FQDN>  
      restartPolicy: Never
