apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.job.namespace }}
  name: cm-update-cluster-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
    
