apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-admin-cm-update-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cm-update-cluster-role
subjects:
- kind: ServiceAccount
  name: kubectl-admin-cm-update
  namespace: {{ .Values.job.namespace }}
