# templates/job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.job.namespace }}
  
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.job.name }}
        image: {{.Values.job.image.registry}}/{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
        command: ["python3", "/app/main.py"] 
        env:
        - name: rootcacert
          value: {{ .Values.edgeClusterConfig.rootcacert }}

        - name: domainname
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#domainname>

        - name: server1MgmtIP
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server1MgmtIP>
        - name: server1OsUsername
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server1OsUsername>
        - name: server1OsPassword
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server1OsPassword>
        - name: server1FQDN
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server1FQDN>  

        - name: server2MgmtIP
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server2MgmtIP>
        - name: server2OsUsername
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server2OsUsername>
        - name: server2OsPassword
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server2OsPassword>
        - name: server2FQDN
          value: <path:{{ .Values.edgeClusterConfig.storeId}}/edge-config/data/secrets#server2FQDN>  
      restartPolicy: Never
